### ISSUE TITLE
Spec v3.0

### ISSUE THREAD

**Issue by frozzare** [personnummer/meta#15]
Let's add stuff that the 3.0 specification should include.

* `getAge` and `format` should throw errors.

**Comment by frozzare** [comment]
Let's add object as a option parameter instead of just a boolean for co-ordination numbers, eg. `Function(string|number, object)`

**Comment by frozzare** [comment]
@Johannestegner should `valid` throw an error also?

**Comment by Johannestegner** [comment]
I'm not really sure to be honest, I do think it should not, seeing it is a `true/false` kind of method just based on the naming... What do you think

**Comment by frozzare** [comment]
It's a `true/false` kind of method so I think we should keep it as it is. If a ssn is wrong or something creates a error it will return `false` and it maybe good enough. Maybe not necessary to return the error, since the input value is most likely false and if we did something wrong we would like to catch it from the user of this library.

So I agree, we skip exceptions for `valid`

**Comment by Johannestegner** [comment]
New parse functionality:

The parse method should return a `Personnummer` object, which have basically the same methods (while instance related instead of static) as the static methods have. _(It would probably be a good idea to store all the different parts of the number pre-parsed instead of forcing it to re-run the parse method each time)_.

See the `parse` method as sort of a factory, while the static ones are more of "i just want to validate this number" or "I just want to check the age on this one" convenience methods.

```
interface Personnummer {
  get Year;
  get Month;
  get Day;
  get ControlNumbers;
  
  bool isCoordinationNumber();
  int getAge();
  /* ... etc etc ... */
}
```

@frozzare @rasmusbe ping me if I got something wrong or some information is missing! :)

**Comment by dannyhajj** [comment]
Regarding the second comment:
> Let's add object as a option parameter instead of just a boolean for co-ordination numbers, eg. `Function(string|number, object)`, see #9

Can this be language-specific? Or at least do not implement this in the Python package?
In Python, it's more common to have keyword arguments instead of objects. They are more explicit and can be easily documented with the proper default value.

For example, the following two functions, `foo` and `bar`, have almost the same signature.
__The difference, however, is that `bar` will accept and ignore any named parameter other than the defined ones. While `foo` will raise an error._

```python
def foo(param1, param2=False, param3=True):
    pass

def bar(param1, **kwargs):
    param2 = kwargs.get('param2', False)
    param3 = kwargs.get('params3', True)
```

And both can be used like so:

```python
foo('foobar')
foo('foobar', param3=False)
foo('foobar', param2=True)
foo('foobar', param3=False, param2=True)
bar('foobar')
bar('foobar', param3=False)
bar('foobar', param3=False, param2=True)

params = { 'param2': True, 'param3': False }
foo('foobar', **params)
bar('foobar', **params)

foo('foobar', param4=False) # Raises an error for an unexpected keyword argument
bar('foobar', param4=False) # No error, but `param4` will just be ignored.
```

But only `foo` can be used with positional parameters for `param2` and `param3`
```python
foo('foobar', True, False)
bar('foobar', True, False) # This raises an error
```

**Comment by frozzare** [comment]
The spec is out after discussion on slack https://github.com/personnummer/meta#package-specification-v3
