### ISSUE TITLE
Undefined behaviour in `valid` method.

### ISSUE THREAD

**Issue by Johannestegner** [personnummer/meta#19]
When passing `MCYYMMDD-/+XXXX` we handle the parsing differently.  
I thought it would be best to open an issue here so that we can post our conclusions openly.

See https://github.com/personnummer/java/issues/15 for info about a bugreport which have to do with this.

**Comment by ullenius** [comment]
I too thought about this for a while. I even wrote som functioning piece of code I ended up throwing away. I think you made the right decision (https://github.com/personnummer/java/issues/15#issuecomment-551771176). 

Skatteverket **does not** use the first 4 digits as an indicator of a person's birth date. They use a separate field for this, just look at a Swedish id card. This is because there is a shortage of numbers for certain dates and years.

This class (the Java version) should validate Personal numbers. **Period**. 

I think trying to parse any data out of the `+ -` is `deprecated`. As is parsing birth county ("_län_") and other data that used to be encoded within the personal numbers. The dash or plus sign is a way of formatting output when you have other data at your disposal (birth date in some database). Not a way to determine the validity of the number.

**Comment by frozzare** [comment]
@Johannestegner still an issue?

**Comment by Johannestegner** [comment]
I think it's resolved with new API.

**Comment by frozzare** [comment]
Closing. Feel free to reopen.
