### ISSUE TITLE
[FEATURE] - Support for "reserve numbers" (reservnummer)

### ISSUE THREAD

**Issue by Johannestegner** [personnummer/meta#34]
**Description**

An issue/feature-request was made in the PHP repository (see here: https://github.com/personnummer/php/issues/29 ).
So thought I'd start a discussion here on the meta repo about if we should add this to the API.

**Comment by rasmusbe** [comment]
I think we shouldn't support it since it's not an established standard.

_https://sv.wikipedia.org/wiki/Reservnummer#Format_:
> Socialstyrelsen rekommenderar ett korrekt födelsedatum samt minst en bokstav i de fyra sista siffrorna för att man inte ska råka skapa ett befintligt personnummer, men utöver det finns det inget fastlagt format

> Socialstyrelsen hittade tre olika varianter av reservnummer i patientregistret för 2008:
Ca 12 000 hade en eller flera bokstäver i de fyra sista fälten och korrekt födelsedatum
Ca 10 000 hade ett nummer som börjar med 50-99 och resten är ett löpnummer av olika sort
Ca 3 000 har ett löpnummer

**Comment by Johannestegner** [comment]
Closing issue as it is not part of standard and core team decided on not implementing it.
