### ISSUE TITLE
Options for valid method

### ISSUE THREAD

**Issue by frozzare** [personnummer/meta#9]
We should add a options to `valid` method to disable coordination number as discussed in https://github.com/personnummer/python/issues/5

Something like this:

```
personnummer.valid(number, { coordination: false })
```

We should also update the package specification [readme.md](https://github.com/personnummer/meta/)

ping @Johannestegner

**Comment by Johannestegner** [comment]
Yes, this is probably a good idea. Should the coordination number be `true` or `false` by default though? 

I feel it will be a breaking change if we set it to not be included as default, as is have been "active"by default since implementation.

**Comment by frozzare** [comment]
We shouldn't break anything so coordination number should be true by default. It's also a valid personnummer :)

**Comment by frozzare** [comment]
After some discussion on slack, we'll add this v3 of the spec. #15 

`Function(string|number, object)`

Example

```
Valid(ssn, { coordinationNumber: false })
```

ping @Johannestegner

**Comment by dannyhajj** [comment]
I first posted this in #15, but I'll delete the other comment and move the discussion here.

Regarding accepting an object as a second parameter.

Can this be language-specific? Or at least do not implement this in the Python package?
In Python, it's more common to have keyword arguments instead of objects. They are more explicit and can be easily documented with the proper default value.

For example, the following two functions, `foo` and `bar`, have almost the same signature.
__The difference, however, is that `bar` will accept and ignore any named parameter other than the defined ones. While `foo` will raise an error._

```python
def foo(param1, param2=False, param3=True):
    pass

def bar(param1, **kwargs):
    param2 = kwargs.get('param2', False)
    param3 = kwargs.get('params3', True)
```

And both can be used like so:

```python
foo('foobar')
foo('foobar', param3=False)
foo('foobar', param2=True)
foo('foobar', param3=False, param2=True)
bar('foobar')
bar('foobar', param3=False)
bar('foobar', param3=False, param2=True)

params = { 'param2': True, 'param3': False }
foo('foobar', **params)
bar('foobar', **params)

foo('foobar', param4=False) # Raises an error for an unexpected keyword argument
bar('foobar', param4=False) # No error, but `param4` will just be ignored.
```

But only `foo` can be used with positional parameters for `param2` and `param3`
```python
foo('foobar', True, False)
bar('foobar', True, False) # This raises an error
```

**Comment by frozzare** [comment]
@dannyhajj 

First of all I will say thank you to your great comment about how this works in python and giving us input about language-specifics issues.

We have had a discussion about this and to allow language-specific code for both options and how errors are handeld. We will up the spec document and #15 about all that we decided about what v3 should contain.
